### ISSUE TITLE
Leftover zoom username

### ISSUE THREAD

**Issue by RasheedAZ** [giantpinkrobots/flatsweep#16]
Hi. I used Zoom from Flathub a while back and mistakenly left the "remember name" checked. If I run Flatsweep, and then install Zoom later, it still remembers my old name from before. 

I unchecked the box, used Zoom, uninstalled it and then ran Flatsweep then installed Zoom again to check if my old name was there, and it still was.

After running Flatsweep, I also ran `flatpak uninstall --delete-data -y -v` just in case.

**Comment by giantpinkrobots** [comment]
Hm. What I guess is happening is that Zoom stores user information in a directory that is different than the stamdard Flatpak user data place.

**Comment by giantpinkrobots** [comment]
Did the "flatpak uninstall --delete-data -y -v" command succesfully remove the user data?

**Comment by RasheedAZ** [comment]
> Did the "flatpak uninstall --delete-data -y -v" command succesfully remove the user data?

No, it didn't. The old username is still showing even though I unchecked remember :(

**Comment by giantpinkrobots** [comment]
Hm. I think what I said initially was correct then. Zoom is probably storing files in arbitrary locations that are not standard Flatpak install directories. In that case, it's not possible for Flatsweep to know these files' existance without having their locations hard coded directly into it, which I don't plan on doing because it would be a nightmare to track every single app (alongside all their updates to check if something changed) that does this.

Also, no need to justify your usage of Zoom haha, it pretty much became the industry standard at this point.

**Comment by giantpinkrobots** [comment]
Closing this for now since there doesn't seem to be a good way of doing this. Please reopen if there is an idea on how to do it that comes to mind.

**Comment by RasheedAZ** [comment]
Hi. I just noticed that there's a .zoom folder in my home directory - that's probably where it stored. Perhaps you can add this location to flatsweep. Noticed other programs also storing data there like:
- audacity
- avidemux
- logseq
- natron
- gramps
- openshot
- ytDownloader
- vscode-oss
etc.
-

**Comment by giantpinkrobots** [comment]
> Hi. I just noticed that there's a .zoom folder in my home directory - that's probably where it stored. Perhaps you can add this location to flatsweep. Noticed other programs also storing data there like:
> 
> * audacity
> * avidemux
> * logseq
> * natron
> * gramps
> * openshot
> * ytDownloader
> * vscode-oss
>   etc.

I understand. However, I still don't think it's a good idea to put that functionality into Flatsweep, because like I said it would be quite a monumental task to track every app that stores data outside of the Flatpak sandbox. Then it'd become a general app cleanup tool rather than a Flatpak cleanup tool. I feel like that is outside of this project's scope.
