### ISSUE TITLE
De-/Select all button

### ISSUE THREAD

**Issue by lightonflux** [giantpinkrobots/flatsweep#23]
I think having the default that everything is selected can have negative consequences. E.g. if a user that is unfamiliar with Flatpak does not recognise the name but expects that the user data is still present in the future (like traditional apps). 

Also if you want to keep some data you have to unselect it manually. IMHO a destructive action like a delete of potentially several GB of user data should not be the default.  

Either way it would be helpful to have a button that un-/selects everything. Especially for those cases where one wants to keep the majority with the current default, or delete most files with the unselected default.

**Comment by giantpinkrobots** [comment]
I have added a select/unselect all button now. I think that is a good idea. But I still think all checkboxes should be selected by default, because the only function of the app is to remove unused user data. I think people will know the clean button will delete all that user data, because that's what the app is for. Regardless, thanks for the suggestion, I am closing this as completed.
