### ISSUE TITLE
Changing the license on a fork, do I have the right?

### ISSUE THREAD

**Issue by pandaroux007** [giantpinkrobots/flatsweep#38]
Good morning,
I am currently creating a fork of your (very good) software by replacing the `GTK4` library with `wxPython`, under the name [`flatsweep-light`](https://github.com/pandaroux007/flatsweep-light) (again in development), except that I am not very keen on licensing and that all my projects being under MIT license I would also like to put the code under MIT, except you are under MPL. Could you enlighten me on what I am allowed to do or not do with your code?

Note: I am French and I use Google translate to write to you, sorry in advance! I'm a beginner in programming, I only do open-source programs and I don't want to harm anyone, so I find out about my rights and obligations before doing something stupid :innocent:

Thanks again for your work on `flatsweep` software,
Sincerely
Pandaroux007

**Comment by giantpinkrobots** [comment]
Hello.

The MPL 2.0 license still overall requires derivative works to be licensed under the same MPL 2.0 license. However this requirement applies to the individual source code files. As in, if you make edits to a file, that file needs to be released under MPL 2.0. If you make new files, you can release those files under any license you want. This is why it's referred as a "weak copyleft" license. It's more permissive than, for example, the GPL v3 where the entire project will need to be licensed under the GPL, even for new files. But it's less permissive than the MIT or BSD licenses.

In short, yes, the changes you make to individual files must be licensed under the MPL 2. But if you for example, write the wxPython related code in another file and then link it to main.py, the main.py file will still be under MPL 2, but that new file you wrote can be under MIT.

If you plan to replace GTK with wxPython, that already means rewriting much of the program. I think you could instead make another project altogether and learn / take inspiration from Flatsweep on how to do things. That way it's not going to use the original files and you can license it under whatever license you want! I think it could be even easier to do it that way instead of trying to hack in another GUI framework into my subpar quality code. I feel like much of the functionality of Flatsweep is flawed anyways, you probably could do it way better than me.

Finally, I think it's awesome that you're being very considerate. But, as much as it's good to be aware of details regarding licensing when getting involved in FOSS, you should also remember that the main point of them is so that FOSS devs don't get screwed over by some corporate entity that wants to turn their hard work into a proprietary product in order to make money from it. It's not that big of a deal if someone messes up when they're just trying to learn how things go. Doing stupid things is how we learn!

Also I'm not a lawyer so none of what I said is legal advice, bla bla bla, y'know the drill.

*Bonne soirée!* <sub>(Hopefully that's correct)</sub>

**Comment by pandaroux007** [comment]
Hello and thank you for your quick response!
Google translate allowed me to understand a large part of your message, only this part remains unclear to me (I don't know if you are speaking with irony or you seriously think that your code is not good - it is used by thousands of people and works very well :+1:!)
> I think it could be even easier to do it that way instead of trying to hack in another GUI framework into my subpar quality code. I feel like much of the functionality of Flatsweep is flawed anyways, you probably could do it way better than me.

I simply want to relocate the GUI library so that the software is integrated into the system outside of GNOME (look for example under Linux Mint 22):
![Flatsweep vs cross-platform software](https://github.com/user-attachments/assets/0a064adf-9095-4111-b67a-65aaea9f5048)

I find your software very well designed, and this is **the only thing** I find fault with it.
So I'm going to take your advice and create a project of my own (don't you mind that this one is called `flatsweep-light`? I can change it if that doesn't suit you!). That said, after diving into your code yesterday, I'm not sure I understand how it works - knowing that I would like to do it only in python, not knowing the `meson` (:thinking:) - between the translation files and the use of GTK4 which I do not know, I have difficulty understanding the main operation of the software (the discovery and deletion of unnecessary flatpack files)... I apologize again if you have thought that I find your software bad, know that this is not the case at all! Also for my questions about your code, if I understand how it works I undertake to provide you with documentation if you wish for your code in `readme.md` format.

> Bonne soirée! (Hopefully that's correct) 

Yes, it's okey! (without google translate :wink:)

Sincerely,
Pandaroux007

**Comment by giantpinkrobots** [comment]
Sure, I'm cool with you calling it Flatsweep Light.

Basically what it does is that it scans through the default Flatpak user data directories (in ~/.var/app), and then checks if those directories also exist in the default Flatpak app installation directories (/var/lib/flatpak/app and ~/.local/share/flatpak/app) and if there exists user data for an app that doesn't appear in the installation directories, that means that app was uninstalled but the user data remains. The "initiate" function in main.py determines all that and adds them into the "self.leftoverData" list. Then the "clean" function removes all the leftover data directories. The rest of the code is handling the Gtk4 interface, and things like the initial warning about default directories, opening the data folder in a file browser when clicked on, etc.

About the documentation, you can do it if you want but I wouldn't bother if I were you. Because this is not the type of program that needs constant development really. It was designed as a very simple app from the get-go.

And no, it's not like I thought you found my program bad, it's that it definitely has a lot of areas where it can be improved I think.

I will be closing this issue if you don't have any other questions. Take care!

**Comment by pandaroux007** [comment]
Good morning,
Once again, thank you for your clarification and your speed!
I take note of your explanations :+1:

I don't think I have any more questions, thanks again for your help and great software!

Sincerely,
Pandaroux007
